/**
 * Pages Function for /500.
 *
 * Static-site routes always come back with HTTP 200 from CF Pages. For our
 * branded 500 page to function as a real error response — pointable by a
 * Worker, a fetch handler, monitoring, etc. — the status must be 500.
 *
 * We do NOT proxy via env.ASSETS.fetch('/500.html'): Pages' clean-URL routing
 * 308-redirects that path back to /500, which is this same function. That
 * recursion silently terminates with an empty body, and an empty 500 makes
 * browsers offer to download the response as a zero-byte file.
 *
 * Instead we serve a fully-inlined HTML body that is regenerated by
 * scripts/build-cf-error-pages.mjs (same artifact as the CF zone-level
 * Custom Pages upload, so a single source of truth).
 */
import { html500 } from './_500-body';

export const onRequest: PagesFunction = async () =>
  new Response(html500, {
    status: 500,
    statusText: 'Internal Server Error',
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store, must-revalidate',
      'X-Content-Type-Options': 'nosniff',
    },
  });
