// AUTO-GENERATED by scripts/gen-apps.mjs — do not edit by hand.
// 11 real Pilot catalogue apps + curated placeholders for the full store vision.

export interface AppMethod { name: string; summary?: string; }
export interface AppChangelog { version: string; date?: string | null; notes: string[]; }
export interface AppBundle { platform: string; bytes: number; }
export interface AppDependency { id: string; reason: string; optional?: boolean; }
export interface AppIcon { mode: 'mask' | 'image'; img: string | null; fit: string | null; pos: string | null; color: string; ink: boolean; file: string | null; hue: number; }
export interface App {
  id: string; name: string; tagline: string; description: string;
  categories: string[]; primaryCategory: string; keywords: string[];
  version: string; vendor: string; vendorUrl: string | null; license: string;
  sourceUrl: string | null; homepage: string | null;
  methods: AppMethod[]; changelog: AppChangelog[]; grants: string[];
  bundles: AppBundle[]; installedBytes: number;
  rating: number; ratingCount: number; ratingHistogram: number[]; downloads: number;
  depends: AppDependency[]; protection: 'shareable' | 'guarded';
  featured: boolean; editorsChoice: boolean; isNew: boolean; real: boolean;
  icon: AppIcon; minPilotVersion: string; runtimes: string[];
  publishedAt: string | null; updatedAt: string | null;
}
export interface Category { id: string; name: string; blurb: string; hue: number; }

export const categories: Category[] = [
  {
    "id": "data",
    "name": "Data & Storage",
    "blurb": "Databases, caches, and stores an agent can stand up in one command.",
    "hue": 125
  },
  {
    "id": "ai",
    "name": "AI & Search",
    "blurb": "Grounded search, retrieval, and generation for agents.",
    "hue": 265
  },
  {
    "id": "web",
    "name": "Web & Automation",
    "blurb": "Turn the live web into clean text and drive real browsers.",
    "hue": 200
  },
  {
    "id": "infra",
    "name": "Infrastructure",
    "blurb": "Containers, microVMs, and deploys — the compute layer for agents.",
    "hue": 30
  },
  {
    "id": "security",
    "name": "Security",
    "blurb": "Guardrails, firewalls, and isolation for agents and their inputs.",
    "hue": 5
  },
  {
    "id": "finance",
    "name": "Finance & Payments",
    "blurb": "Settle value on-overlay and read the markets.",
    "hue": 155
  },
  {
    "id": "comms",
    "name": "Comms & Voice",
    "blurb": "Phone numbers, messaging, and threaded conversations.",
    "hue": 220
  }
];

export const apps: App[] = [
  {
    "id": "io.pilot.postgres",
    "name": "PostgreSQL",
    "tagline": "The database, agent-native — initdb, psql, and the full client/server toolchain",
    "description": "PostgreSQL 17.5.0 as a native CLI for agents: stand up and manage a local Postgres server (initdb / start / stop / createdb) and run SQL with psql — aligned-table or CSV results, backslash schema introspection, database listing, and the full client/server toolchain (pg_dump, pg_restore, pg_isready, ...) via a verbatim-argv passthrough. Connects to a local or remote server via a libpq connection string or PG* env.",
    "categories": [
      "data"
    ],
    "primaryCategory": "data",
    "keywords": [
      "postgres",
      "sql",
      "database",
      "psql",
      "pg_dump",
      "relational"
    ],
    "version": "17.5.0",
    "vendor": "Pilot Protocol",
    "vendorUrl": null,
    "license": "PostgreSQL",
    "sourceUrl": "https://github.com/postgres/postgres",
    "homepage": "https://www.postgresql.org",
    "methods": [
      {
        "name": "postgres.initdb",
        "summary": "Initialize a new local database cluster."
      },
      {
        "name": "postgres.start",
        "summary": "Start the local Postgres server."
      },
      {
        "name": "postgres.stop",
        "summary": "Stop the local server."
      },
      {
        "name": "postgres.createdb",
        "summary": "Create a database."
      },
      {
        "name": "postgres.psql",
        "summary": "Run SQL — aligned-table or CSV results."
      },
      {
        "name": "postgres.exec",
        "summary": "Verbatim-argv passthrough to the full toolchain (pg_dump, pg_restore, pg_isready, ...)."
      },
      {
        "name": "postgres.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "17.5.0",
        "date": "2026-06-28",
        "notes": [
          "Native-CLI packaging of PostgreSQL 17.5.0 for the Pilot app store",
          "Aligned-table + CSV result modes over IPC",
          "Full client/server toolchain via verbatim-argv passthrough"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "fs.write:$PGDATA",
      "proc.exec:postgres",
      "proc.exec:psql",
      "net.dial:127.0.0.1",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 31400000
      },
      {
        "platform": "darwin-amd64",
        "bytes": 28888000
      },
      {
        "platform": "linux-arm64",
        "bytes": 32970000
      },
      {
        "platform": "linux-amd64",
        "bytes": 31714000
      }
    ],
    "installedBytes": 53380000,
    "rating": 4.6,
    "ratingCount": 1281,
    "ratingHistogram": [
      63,
      69,
      183,
      383,
      583
    ],
    "downloads": 49263,
    "depends": [],
    "protection": "guarded",
    "featured": true,
    "editorsChoice": true,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "mask",
      "img": null,
      "fit": null,
      "pos": null,
      "color": "#4169E1",
      "ink": false,
      "file": "/appicons/io.pilot.postgres.svg",
      "hue": 125
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "native-cli"
    ],
    "publishedAt": "2026-06-28",
    "updatedAt": "2026-06-28"
  },
  {
    "id": "io.pilot.cosift",
    "name": "Cosift",
    "tagline": "Grounded web search, retrieval, and research for agents",
    "description": "Cosift is the Pilot app-store front door for the cosift search/answer/research API. It gives an agent keyword + semantic search, document retrieval, and LLM-grounded answers and multi-step research over a crawled web corpus — returned as clean structured JSON.\n\nEvery method is discoverable at runtime via cosift.help, which reports each method's parameters and a latency class (fast / med / slow) so a caller can pick the cheapest method that fits.",
    "categories": [
      "ai"
    ],
    "primaryCategory": "ai",
    "keywords": [
      "search",
      "rag",
      "answer",
      "research",
      "web",
      "retrieval"
    ],
    "version": "0.1.2",
    "vendor": "Pilot Protocol",
    "vendorUrl": null,
    "license": "MIT",
    "sourceUrl": "https://github.com/pilot-protocol/cosift",
    "homepage": "https://pilotprotocol.network",
    "methods": [
      {
        "name": "cosift.search",
        "summary": "Keyword + semantic search over the crawled corpus"
      },
      {
        "name": "cosift.find_similar",
        "summary": "Find documents similar to a given result"
      },
      {
        "name": "cosift.contents",
        "summary": "Fetch the full contents of a document"
      },
      {
        "name": "cosift.answer",
        "summary": "Single-shot grounded answer with citations"
      },
      {
        "name": "cosift.research",
        "summary": "Multi-step research report over the corpus"
      },
      {
        "name": "cosift.stats",
        "summary": "Corpus and index statistics"
      },
      {
        "name": "cosift.health",
        "summary": "Service health check"
      },
      {
        "name": "cosift.help",
        "summary": "Discovery: methods, params, and latency classes"
      }
    ],
    "changelog": [
      {
        "version": "0.1.2",
        "date": "2026-06-09",
        "notes": [
          "cosift search/answer/research adapter with cosift.help discovery",
          "Installable via the Pilot app store catalogue"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "audit.log:*",
      "net.dial:cosift.pilotprotocol.network",
      "net.dial:127.0.0.1"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 4918122
      },
      {
        "platform": "darwin-amd64",
        "bytes": 5300112
      },
      {
        "platform": "linux-arm64",
        "bytes": 4201891
      },
      {
        "platform": "linux-amd64",
        "bytes": 4201891
      }
    ],
    "installedBytes": 8641298,
    "rating": 4.6,
    "ratingCount": 1845,
    "ratingHistogram": [
      80,
      8,
      343,
      575,
      839
    ],
    "downloads": 69547,
    "depends": [],
    "protection": "shareable",
    "featured": false,
    "editorsChoice": true,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "image",
      "img": "/appicons/io.pilot.cosift.png",
      "fit": "contain",
      "pos": "center",
      "color": "#ffffff",
      "ink": false,
      "file": null,
      "hue": 265
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-09",
    "updatedAt": "2026-06-09"
  },
  {
    "id": "io.pilot.smolmachines",
    "name": "Smol Machines",
    "tagline": "Fast, hardware-isolated microVMs on demand",
    "description": "Smol Machines — the app-store front door for the smolmachines VM engine. It lets an agent spin up fast, hardware-isolated Linux microVMs on demand (sub-second boot, real hypervisor isolation — not shared-kernel containers), then run workloads in a disposable sandbox. Free to use. Portable .smolmachine artifacts run identically on macOS and Linux, locally or in the cloud.\n\nUse it to run untrusted or AI-generated code safely, give an agent a real Linux shell, automate headless browsers, run GPU/compute jobs, and fan out parallel ephemeral workers thanks to sub-second boot.\n\nDiscover the live method surface at runtime with smolmachines.help.",
    "categories": [
      "infra"
    ],
    "primaryCategory": "infra",
    "keywords": [
      "microvm",
      "sandbox",
      "vm",
      "isolation",
      "gpu",
      "ci"
    ],
    "version": "1.2.0",
    "vendor": "smol machines",
    "vendorUrl": "https://smolmachines.com",
    "license": "Apache-2.0",
    "sourceUrl": "https://github.com/smol-machines/smolvm",
    "homepage": "https://smolmachines.com",
    "methods": [
      {
        "name": "smolmachines.exec",
        "summary": "Run any smolvm subcommand in a fast, hardware-isolated Linux microVM."
      },
      {
        "name": "smolmachines.help",
        "summary": "Discovery: every method with params, kind, and latency class."
      }
    ],
    "changelog": [
      {
        "version": "1.2.0",
        "date": "2026-06-20",
        "notes": [
          "Released v1.2.0"
        ]
      },
      {
        "version": "1.1.0",
        "date": "2026-05-30",
        "notes": [
          "Portable .smolmachine artifacts run identically on macOS and Linux",
          "GPU tasks via Vulkan"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "proc.exec:smolvm",
      "fs.read:$APP/install.json",
      "fs.write:$APP",
      "net.dial:pub-f09f9a4ea848491198d48e329ba030e3.r2.dev",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 5880761
      },
      {
        "platform": "darwin-amd64",
        "bytes": 5666915
      },
      {
        "platform": "linux-arm64",
        "bytes": 5078839
      },
      {
        "platform": "linux-amd64",
        "bytes": 5078839
      }
    ],
    "installedBytes": 9140402,
    "rating": 4.9,
    "ratingCount": 1041,
    "ratingHistogram": [
      23,
      9,
      159,
      342,
      506
    ],
    "downloads": 371,
    "depends": [],
    "protection": "guarded",
    "featured": false,
    "editorsChoice": true,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "image",
      "img": "/appicons/io.pilot.smolmachines.png",
      "fit": "contain",
      "pos": "center",
      "color": "#ffffff",
      "ink": false,
      "file": null,
      "hue": 30
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-20",
    "updatedAt": "2026-06-20"
  },
  {
    "id": "io.pilot.sixtyfour",
    "name": "Sixtyfour",
    "tagline": "People- and company-intelligence: discovery, enrichment, and agentic research",
    "description": "Sixtyfour is the app-store front door for the Sixtyfour people-intelligence and company-intelligence API. It gives an agent contact discovery (find email / find phone), reverse lookups from an email or phone, full person and company enrichment, and an agentic QA researcher that answers free-form questions about a person or company. All returned as clean structured JSON, every field source-backed.",
    "categories": [
      "data"
    ],
    "primaryCategory": "data",
    "keywords": [
      "enrichment",
      "people",
      "company",
      "email",
      "phone",
      "lead",
      "research"
    ],
    "version": "0.1.0",
    "vendor": "Sixtyfour",
    "vendorUrl": null,
    "license": "Proprietary",
    "sourceUrl": "https://docs.sixtyfour.ai",
    "homepage": "https://sixtyfour.ai",
    "methods": [
      {
        "name": "sixtyfour.people_intelligence",
        "summary": "Full, source-backed enrichment of a person from seed details."
      },
      {
        "name": "sixtyfour.company_intelligence",
        "summary": "Full, source-backed company profile, optionally with people."
      },
      {
        "name": "sixtyfour.find_email",
        "summary": "Find a verified email for a person from partial details."
      },
      {
        "name": "sixtyfour.find_phone",
        "summary": "Find a phone number for a person from partial details."
      },
      {
        "name": "sixtyfour.reverse_email",
        "summary": "Identify the person and company behind an email address."
      },
      {
        "name": "sixtyfour.qa",
        "summary": "Agentic QA researcher over a person or company, with sources."
      },
      {
        "name": "sixtyfour.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "0.1.0",
        "date": "2026-06-21",
        "notes": [
          "Contact discovery, reverse lookups, person/company enrichment, and an agentic QA researcher — all source-backed structured JSON."
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "key.sign:self",
      "net.dial:broker.pilotprotocol.network",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 4800190
      },
      {
        "platform": "darwin-amd64",
        "bytes": 4604264
      },
      {
        "platform": "linux-arm64",
        "bytes": 4849171
      },
      {
        "platform": "linux-amd64",
        "bytes": 4457319
      }
    ],
    "installedBytes": 8679650,
    "rating": 4.5,
    "ratingCount": 775,
    "ratingHistogram": [
      18,
      7,
      121,
      274,
      356
    ],
    "downloads": 15060,
    "depends": [],
    "protection": "shareable",
    "featured": false,
    "editorsChoice": false,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "image",
      "img": "/appicons/io.pilot.sixtyfour.png",
      "fit": "cover",
      "pos": "center",
      "color": "#0b0b0a",
      "ink": false,
      "file": null,
      "hue": 125
    },
    "minPilotVersion": "1.10.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-21",
    "updatedAt": "2026-06-21"
  },
  {
    "id": "io.pilot.plainweb",
    "name": "Plainweb",
    "tagline": "Any web page as clean Markdown — no HTML, no JS, one call",
    "description": "Plainweb is a Pilot-owned URL→Markdown service: give it any web page and get back clean, accurate Markdown — no HTML, no JavaScript, just plain text structured as Markdown.\n\nOne call — plainweb.fetch(url) fetches the page and returns it as Markdown (GFM tables, fenced code with language, task lists). A cost-aware static→headless-Chrome fetch ladder means most pages never launch Chrome. Free and open — no API key required. Anonymous callers get 1000 requests/second.",
    "categories": [
      "web"
    ],
    "primaryCategory": "web",
    "keywords": [
      "plainweb",
      "markdown",
      "web",
      "fetch",
      "scrape",
      "extract",
      "readability",
      "url"
    ],
    "version": "1.0.0",
    "vendor": "Pilot Protocol",
    "vendorUrl": "https://pilotprotocol.network",
    "license": "Proprietary",
    "sourceUrl": "https://github.com/pilot-protocol/plainweb",
    "homepage": "https://pilotprotocol.network",
    "methods": [
      {
        "name": "plainweb.fetch",
        "summary": "Fetch any web page and return it as clean Markdown — no HTML, no JavaScript."
      },
      {
        "name": "plainweb.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "1.0.0",
        "date": "2026-06-14",
        "notes": [
          "Released v1.0.0",
          "go-readability primary with go-trafilatura fallback, html-to-markdown v2"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "net.dial:plainweb-hu4fob755a-uc.a.run.app",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 5085436
      },
      {
        "platform": "darwin-amd64",
        "bytes": 4481226
      },
      {
        "platform": "linux-arm64",
        "bytes": 4934383
      },
      {
        "platform": "linux-amd64",
        "bytes": 5135787
      }
    ],
    "installedBytes": 8625202,
    "rating": 4.8,
    "ratingCount": 1018,
    "ratingHistogram": [
      18,
      14,
      152,
      341,
      493
    ],
    "downloads": 59342,
    "depends": [],
    "protection": "shareable",
    "featured": false,
    "editorsChoice": true,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "image",
      "img": "/appicons/io.pilot.plainweb.png",
      "fit": "contain",
      "pos": "center",
      "color": "#ffffff",
      "ink": false,
      "file": null,
      "hue": 200
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-14",
    "updatedAt": "2026-06-14"
  },
  {
    "id": "io.pilot.slipstream",
    "name": "Slipstream",
    "tagline": "Polymarket smart-money leaderboard, signals, tape & opportunities",
    "description": "SLIPSTREAM — a Polymarket smart-money leaderboard, live signals, tape, and opportunity feed, delivered over an Ed25519-signed API. Track the wallets that move prediction markets, surface fresh edges, and read the tape as structured JSON an agent can act on.",
    "categories": [
      "finance"
    ],
    "primaryCategory": "finance",
    "keywords": [
      "polymarket",
      "signals",
      "leaderboard",
      "markets",
      "tape",
      "prediction"
    ],
    "version": "1.0.0",
    "vendor": "Pilot Protocol",
    "vendorUrl": null,
    "license": "MIT",
    "sourceUrl": "https://github.com/pilot-protocol/catalog",
    "homepage": "https://pilotprotocol.network",
    "methods": [
      {
        "name": "slipstream.leaderboard",
        "summary": "Smart-money leaderboard, ranked."
      },
      {
        "name": "slipstream.signals",
        "summary": "Live trade signals from tracked wallets."
      },
      {
        "name": "slipstream.tape",
        "summary": "Raw market tape as structured JSON."
      },
      {
        "name": "slipstream.opportunities",
        "summary": "Ranked opportunity feed."
      },
      {
        "name": "slipstream.help",
        "summary": "Discovery: methods, params, and latency classes."
      }
    ],
    "changelog": [
      {
        "version": "1.0.0",
        "date": "2026-06-18",
        "notes": [
          "Ed25519-signed API for leaderboard, signals, tape, and opportunities"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "net.dial:slipstream.pilotprotocol.network",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 4160673
      },
      {
        "platform": "darwin-amd64",
        "bytes": 4347670
      },
      {
        "platform": "linux-arm64",
        "bytes": 5142405
      },
      {
        "platform": "linux-amd64",
        "bytes": 4207423
      }
    ],
    "installedBytes": 7947354,
    "rating": 4.7,
    "ratingCount": 846,
    "ratingHistogram": [
      30,
      26,
      139,
      263,
      387
    ],
    "downloads": 39262,
    "depends": [],
    "protection": "shareable",
    "featured": false,
    "editorsChoice": false,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "mask",
      "img": null,
      "fit": null,
      "pos": null,
      "color": "oklch(0.6 0.19 155)",
      "ink": false,
      "file": "/appicons/io.pilot.slipstream.svg",
      "hue": 155
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-18",
    "updatedAt": "2026-06-18"
  },
  {
    "id": "io.pilot.miren",
    "name": "Miren",
    "tagline": "Operate the Miren PaaS from an agent: deploy, roll back, and debug apps",
    "description": "Miren is a deployment platform for small teams. This app is the app-store front door for the miren CLI, letting an agent drive a Miren PaaS over IPC.\n\nDeploy lifecycle (deploy, analyze, rollback), inspect apps (status, history, JSON logs), server & diagnostics (doctor, whoami, connection debug), and a full-CLI passthrough via miren.exec. Structured JSON wherever the CLI offers it; discover the live surface with miren.help.",
    "categories": [
      "infra"
    ],
    "primaryCategory": "infra",
    "keywords": [
      "miren",
      "paas",
      "deploy",
      "server",
      "debug",
      "infrastructure",
      "devops",
      "logs",
      "cli"
    ],
    "version": "0.1.0",
    "vendor": "Miren",
    "vendorUrl": "https://miren.dev",
    "license": "Proprietary",
    "sourceUrl": "https://github.com/mirendev",
    "homepage": "https://miren.dev",
    "methods": [
      {
        "name": "miren.deploy",
        "summary": "Build and deploy the app in the current directory (non-interactive)."
      },
      {
        "name": "miren.rollback",
        "summary": "Roll an application back to its previous deployed version."
      },
      {
        "name": "miren.apps",
        "summary": "List all applications on the cluster."
      },
      {
        "name": "miren.logs",
        "summary": "Read recent logs for an application as JSON."
      },
      {
        "name": "miren.doctor",
        "summary": "Diagnose the miren environment and connectivity."
      },
      {
        "name": "miren.exec",
        "summary": "Run any verbatim miren argv (addon, auth, env, route, cluster, ...)."
      },
      {
        "name": "miren.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "0.1.0",
        "date": "2026-06-22",
        "notes": [
          "Deploy/rollback, status/logs/history, server & diagnostics, plus a passthrough exec for any miren subcommand."
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "proc.exec:miren",
      "net.dial:*.miren.dev",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 3136025
      },
      {
        "platform": "darwin-amd64",
        "bytes": 2565839
      },
      {
        "platform": "linux-arm64",
        "bytes": 2708385
      },
      {
        "platform": "linux-amd64",
        "bytes": 2708385
      }
    ],
    "installedBytes": 5020350,
    "rating": 4.4,
    "ratingCount": 392,
    "ratingHistogram": [
      12,
      49,
      96,
      147,
      88
    ],
    "downloads": 32318,
    "depends": [],
    "protection": "shareable",
    "featured": false,
    "editorsChoice": false,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "image",
      "img": "/appicons/io.pilot.miren.png",
      "fit": "cover",
      "pos": "center",
      "color": "#1b6ef3",
      "ink": false,
      "file": null,
      "hue": 30
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-22",
    "updatedAt": "2026-06-22"
  },
  {
    "id": "io.pilot.otto",
    "name": "Otto",
    "tagline": "Drive real Chrome tabs from an agent — extract, automate, screenshot",
    "description": "Otto is secure remote browser automation. A controller CLI sends commands over an authenticated WebSocket to a relay daemon, which routes them to a Chrome extension running on live tabs. Code drives the browser deterministically; the agent decides what to do, not how to click.\n\nContent extraction (URL → markdown/HTML/text), site commands (Reddit/LinkedIn/Hacker News/Google), page & tab control (screenshots, low-level primitives), and a full-CLI passthrough. Real browser tabs, not a headless farm.",
    "categories": [
      "web"
    ],
    "primaryCategory": "web",
    "keywords": [
      "otto",
      "browser",
      "automation",
      "chrome",
      "scraping",
      "extract",
      "screenshot",
      "relay"
    ],
    "version": "0.20.0",
    "vendor": "Telepat",
    "vendorUrl": "https://telepat.io",
    "license": "MIT",
    "sourceUrl": "https://github.com/telepat-io/otto",
    "homepage": "https://docs.telepat.io/otto",
    "methods": [
      {
        "name": "otto.extract",
        "summary": "Extract readable page content through a live paired browser tab, as markdown JSON."
      },
      {
        "name": "otto.screenshot",
        "summary": "Capture a viewport or full-page screenshot through a live tab."
      },
      {
        "name": "otto.test",
        "summary": "Run a registered site command (getPosts, getFrontPage, ...) on a browser node."
      },
      {
        "name": "otto.status",
        "summary": "Relay daemon status + connected browser node IDs."
      },
      {
        "name": "otto.exec",
        "summary": "Run any verbatim otto argv."
      },
      {
        "name": "otto.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "0.20.0",
        "date": "2026-06-25",
        "notes": [
          "Released v0.20.0"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "proc.exec:otto",
      "net.dial:127.0.0.1",
      "net.listen:127.0.0.1",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 4766707
      },
      {
        "platform": "darwin-amd64",
        "bytes": 5409409
      },
      {
        "platform": "linux-arm64",
        "bytes": 5891435
      },
      {
        "platform": "linux-amd64",
        "bytes": 5677201
      }
    ],
    "installedBytes": 9633952,
    "rating": 4.6,
    "ratingCount": 1683,
    "ratingHistogram": [
      31,
      23,
      256,
      512,
      861
    ],
    "downloads": 76097,
    "depends": [],
    "protection": "guarded",
    "featured": false,
    "editorsChoice": false,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "image",
      "img": "/appicons/io.pilot.otto.png",
      "fit": "cover",
      "pos": "center",
      "color": "#ffffff",
      "ink": false,
      "file": null,
      "hue": 200
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-25",
    "updatedAt": "2026-06-25"
  },
  {
    "id": "io.pilot.agentphone",
    "name": "Agent Phone",
    "tagline": "Give your agent a real phone number: voice, SMS, and iMessage over REST",
    "description": "Give your agent a real phone number: place and receive voice calls, send and receive SMS/iMessage, and hold threaded conversations — all over REST. Provision a number, create a calling agent, place a call and poll its transcript, send a text and poll for replies.",
    "categories": [
      "comms"
    ],
    "primaryCategory": "comms",
    "keywords": [
      "phone",
      "voice",
      "sms",
      "imessage",
      "calls",
      "number",
      "rest"
    ],
    "version": "0.1.0",
    "vendor": "Pilot Protocol",
    "vendorUrl": null,
    "license": "Proprietary",
    "sourceUrl": "https://github.com/pilot-protocol/agentphone",
    "homepage": "https://pilotprotocol.network",
    "methods": [
      {
        "name": "agentphone.provision",
        "summary": "Provision a phone number."
      },
      {
        "name": "agentphone.call",
        "summary": "Place a voice call; poll for the transcript."
      },
      {
        "name": "agentphone.text",
        "summary": "Send an SMS/iMessage; poll for replies."
      },
      {
        "name": "agentphone.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "0.1.0",
        "date": "2026-06-24",
        "notes": [
          "Provision a number, place calls, send texts, and hold threaded conversations over REST."
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "net.dial:agentphone.pilotprotocol.network",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 4100000
      },
      {
        "platform": "darwin-amd64",
        "bytes": 4100000
      },
      {
        "platform": "linux-arm64",
        "bytes": 3977000
      },
      {
        "platform": "linux-amd64",
        "bytes": 3813000
      }
    ],
    "installedBytes": 6970000,
    "rating": 4.3,
    "ratingCount": 1572,
    "ratingHistogram": [
      17,
      193,
      386,
      579,
      397
    ],
    "downloads": 34832,
    "depends": [],
    "protection": "shareable",
    "featured": false,
    "editorsChoice": false,
    "isNew": true,
    "real": true,
    "icon": {
      "mode": "mask",
      "img": null,
      "fit": null,
      "pos": null,
      "color": "oklch(0.6 0.19 220)",
      "ink": false,
      "file": "/appicons/io.pilot.agentphone.svg",
      "hue": 220
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-24",
    "updatedAt": "2026-06-24"
  },
  {
    "id": "io.telepat.ideon-free",
    "name": "Ideon (Free)",
    "tagline": "Free long-form article generation for agents",
    "description": "Free article generation for agents: ideon-free.generate(idea) returns a jobId; ideon-free.poll(jobId) returns the finished markdown article. A thin adapter over Ideon's ideon_write — no payment.",
    "categories": [
      "ai"
    ],
    "primaryCategory": "ai",
    "keywords": [
      "writing",
      "article",
      "generate",
      "markdown",
      "content",
      "ideon"
    ],
    "version": "0.3.1",
    "vendor": "Telepat",
    "vendorUrl": "https://telepat.io",
    "license": "Proprietary",
    "sourceUrl": "https://telepat.io",
    "homepage": "https://telepat.io",
    "methods": [
      {
        "name": "ideon-free.generate",
        "summary": "Submit an idea; returns a jobId."
      },
      {
        "name": "ideon-free.poll",
        "summary": "Poll a jobId; returns the finished markdown article."
      },
      {
        "name": "ideon-free.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "0.3.1",
        "date": "2026-06-16",
        "notes": [
          "Thin adapter over Ideon ideon_write — no payment."
        ]
      }
    ],
    "grants": [
      "audit.log:*",
      "net.dial:ideon-mcp.telepat.io"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 828000
      },
      {
        "platform": "darwin-amd64",
        "bytes": 828000
      },
      {
        "platform": "linux-arm64",
        "bytes": 945000
      },
      {
        "platform": "linux-amd64",
        "bytes": 981000
      }
    ],
    "installedBytes": 13824,
    "rating": 4.2,
    "ratingCount": 1613,
    "ratingHistogram": [
      61,
      240,
      368,
      564,
      380
    ],
    "downloads": 69030,
    "depends": [],
    "protection": "guarded",
    "featured": false,
    "editorsChoice": false,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "image",
      "img": "/appicons/io.telepat.ideon-free.png",
      "fit": "cover",
      "pos": "center",
      "color": "#0b0b0a",
      "ink": false,
      "file": null,
      "hue": 265
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-16",
    "updatedAt": "2026-06-16"
  },
  {
    "id": "io.pilot.wallet",
    "name": "Wallet",
    "tagline": "On-overlay USDC payments across Base, Ethereum, and Polygon",
    "description": "The Pilot reference wallet brings x402 + EIP-3009 USDC payments to the overlay, with spend caps the supervisor enforces. One secp256k1 address works across all three USDC mainnets (Base, Ethereum, Polygon); per-chain RPC is configurable via PILOT_EVM_RPC_<chainID>.\n\nInstalling this app lets other apps and agents settle payments without leaving the network. Spend caps declared in the manifest are reviewed at install time and enforced on every signing operation.",
    "categories": [
      "finance"
    ],
    "primaryCategory": "finance",
    "keywords": [
      "usdc",
      "x402",
      "eip-3009",
      "evm",
      "base",
      "ethereum",
      "polygon",
      "payments"
    ],
    "version": "0.3.3",
    "vendor": "Pilot Protocol",
    "vendorUrl": "https://pilotprotocol.network",
    "license": "AGPL-3.0-or-later",
    "sourceUrl": "https://github.com/pilot-protocol/wallet",
    "homepage": "https://pilotprotocol.network",
    "methods": [
      {
        "name": "wallet.pay",
        "summary": "Settle an x402 / EIP-3009 USDC payment."
      },
      {
        "name": "wallet.balance",
        "summary": "Read balances across configured chains."
      },
      {
        "name": "wallet.evm.chains",
        "summary": "List configured EVM chains for the wallet."
      },
      {
        "name": "wallet.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "0.3.3",
        "date": "2026-06-08",
        "notes": [
          "Default --evm-chains expands to 8453,1,137 so supervised wallets get all three USDC mainnets out of the box",
          "PILOT_EVM_CHAINS env overrides the default chain set"
        ]
      },
      {
        "version": "0.3.2",
        "date": "2026-06-08",
        "notes": [
          "Multichain EVM: same secp256k1 address across Base, Ethereum, Polygon",
          "New wallet.evm.chains method; all evm.* methods accept an optional chain_id"
        ]
      },
      {
        "version": "0.3.1",
        "date": "2026-06-08",
        "notes": [
          "Wired the wallet.evm.* methods into the binary",
          "Added --evm-identity, --evm-chain, --evm-rpc, --no-evm flags"
        ]
      },
      {
        "version": "0.3.0",
        "date": "2026-06-08",
        "notes": [
          "Signed wallet app bundle: ed25519-signed manifest, sha256-pinned binary"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "key.sign:self",
      "net.dial:*.base.org",
      "net.dial:*.infura.io",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 8564113
      },
      {
        "platform": "darwin-amd64",
        "bytes": 8928543
      },
      {
        "platform": "linux-arm64",
        "bytes": 9384081
      },
      {
        "platform": "linux-amd64",
        "bytes": 9384081
      }
    ],
    "installedBytes": 15488289,
    "rating": 4.6,
    "ratingCount": 1036,
    "ratingHistogram": [
      23,
      9,
      159,
      341,
      504
    ],
    "downloads": 47385,
    "depends": [],
    "protection": "guarded",
    "featured": false,
    "editorsChoice": true,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "image",
      "img": "/appicons/io.pilot.wallet.png",
      "fit": "contain",
      "pos": "center",
      "color": "#ffffff",
      "ink": false,
      "file": null,
      "hue": 155
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "go"
    ],
    "publishedAt": "2026-06-08",
    "updatedAt": "2026-06-08"
  },
  {
    "id": "io.pilot.duckdb",
    "name": "DuckDB",
    "tagline": "In-process analytical SQL — columnar, embedded, fast",
    "description": "DuckDB 1.5.4 as a native CLI for agents: an in-process analytical (OLAP) database that runs SQL directly over CSV, Parquet, JSON, and its own columnar format — no server to stand up. Run queries and get aligned-table or CSV/JSON results, attach and query files in place, and reach the full DuckDB CLI surface via a verbatim-argv passthrough.\n\nEvery method is discoverable at runtime via duckdb.help, which reports each method's parameters and a latency class (fast / med / slow).",
    "categories": [
      "data"
    ],
    "primaryCategory": "data",
    "keywords": [
      "duckdb",
      "olap",
      "columnar",
      "analytics",
      "sql",
      "parquet",
      "embedded"
    ],
    "version": "1.5.4",
    "vendor": "DuckDB Labs",
    "vendorUrl": "https://duckdb.org",
    "license": "MIT",
    "sourceUrl": "https://github.com/duckdb/duckdb",
    "homepage": "https://duckdb.org",
    "methods": [
      {
        "name": "duckdb.query",
        "summary": "Run SQL — aligned-table, CSV, or JSON results."
      },
      {
        "name": "duckdb.exec",
        "summary": "Verbatim-argv passthrough to the full DuckDB CLI."
      },
      {
        "name": "duckdb.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "1.5.4",
        "date": "2026-06-27",
        "notes": [
          "Native-CLI packaging of DuckDB 1.5.4 for the Pilot app store",
          "Aligned-table + CSV + JSON result modes over IPC",
          "Query Parquet / CSV / JSON files in place"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "fs.read:*",
      "fs.write:$APP",
      "proc.exec:duckdb",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 21824000
      },
      {
        "platform": "darwin-amd64",
        "bytes": 23808000
      },
      {
        "platform": "linux-arm64",
        "bytes": 27032000
      },
      {
        "platform": "linux-amd64",
        "bytes": 22072000
      }
    ],
    "installedBytes": 42160000,
    "rating": 4.6,
    "ratingCount": 1257,
    "ratingHistogram": [
      17,
      22,
      198,
      413,
      606
    ],
    "downloads": 76477,
    "depends": [],
    "protection": "guarded",
    "featured": true,
    "editorsChoice": true,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "mask",
      "img": null,
      "fit": null,
      "pos": null,
      "color": "#FFF000",
      "ink": true,
      "file": "/appicons/io.pilot.duckdb.svg",
      "hue": 125
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "native-cli"
    ],
    "publishedAt": "2026-06-27",
    "updatedAt": "2026-06-27"
  },
  {
    "id": "io.pilot.redis",
    "name": "Redis",
    "tagline": "In-memory data store, cache, and message broker",
    "description": "Redis 8.6.2 as a native CLI for agents: stand up and manage a local Redis server (start / stop) and drive it with redis-cli — strings, hashes, lists, sets, sorted sets, streams, and pub/sub, all as structured results. The full client/server toolchain is reachable via a verbatim-argv passthrough; connect to a local or remote server via a connection URL or REDIS* env.\n\nEvery method is discoverable at runtime via redis.help.",
    "categories": [
      "data"
    ],
    "primaryCategory": "data",
    "keywords": [
      "redis",
      "cache",
      "kv",
      "in-memory",
      "pubsub",
      "streams",
      "broker"
    ],
    "version": "8.6.2",
    "vendor": "Redis",
    "vendorUrl": "https://redis.io",
    "license": "RSALv2",
    "sourceUrl": "https://github.com/redis/redis",
    "homepage": "https://redis.io",
    "methods": [
      {
        "name": "redis.start",
        "summary": "Start a local Redis server."
      },
      {
        "name": "redis.stop",
        "summary": "Stop the local server."
      },
      {
        "name": "redis.cli",
        "summary": "Run a command via redis-cli; structured results."
      },
      {
        "name": "redis.exec",
        "summary": "Verbatim-argv passthrough to the full toolchain."
      },
      {
        "name": "redis.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "8.6.2",
        "date": "2026-06-26",
        "notes": [
          "Native-CLI packaging of Redis 8.6.2 for the Pilot app store",
          "Local server lifecycle (start / stop) over IPC",
          "redis-cli with structured results"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "fs.write:$APP",
      "proc.exec:redis-server",
      "proc.exec:redis-cli",
      "net.dial:127.0.0.1",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 17108000
      },
      {
        "platform": "darwin-amd64",
        "bytes": 16380000
      },
      {
        "platform": "linux-arm64",
        "bytes": 17290000
      },
      {
        "platform": "linux-amd64",
        "bytes": 17290000
      }
    ],
    "installedBytes": 30940000,
    "rating": 4.6,
    "ratingCount": 1941,
    "ratingHistogram": [
      9,
      86,
      361,
      593,
      893
    ],
    "downloads": 16477,
    "depends": [],
    "protection": "guarded",
    "featured": false,
    "editorsChoice": true,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "mask",
      "img": null,
      "fit": null,
      "pos": null,
      "color": "#FF4438",
      "ink": false,
      "file": "/appicons/io.pilot.redis.svg",
      "hue": 125
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "native-cli"
    ],
    "publishedAt": "2026-06-26",
    "updatedAt": "2026-06-26"
  },
  {
    "id": "io.pilot.docker",
    "name": "Docker",
    "tagline": "Build and run OCI containers from an agent — Linux hosts",
    "description": "Docker Engine 29.6.1 packaged as a native app for agents on Linux: build images, run and manage containers, and drive the full docker CLI over a verbatim-argv passthrough — structured JSON wherever the CLI offers it.\n\nLinux only. The Docker daemon needs a Linux kernel, so this app runs on Linux hosts (arm64 + amd64); it is not available on macOS. Every method is discoverable at runtime via docker.help.",
    "categories": [
      "infra"
    ],
    "primaryCategory": "infra",
    "keywords": [
      "docker",
      "containers",
      "oci",
      "images",
      "build",
      "linux"
    ],
    "version": "29.6.1",
    "vendor": "Docker",
    "vendorUrl": "https://www.docker.com",
    "license": "Apache-2.0",
    "sourceUrl": "https://github.com/moby/moby",
    "homepage": "https://www.docker.com",
    "methods": [
      {
        "name": "docker.run",
        "summary": "Run a container from an image."
      },
      {
        "name": "docker.build",
        "summary": "Build an image from a Dockerfile/context."
      },
      {
        "name": "docker.ps",
        "summary": "List containers as JSON."
      },
      {
        "name": "docker.exec",
        "summary": "Verbatim-argv passthrough to the full docker CLI."
      },
      {
        "name": "docker.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "29.6.1",
        "date": "2026-06-30",
        "notes": [
          "Native-CLI packaging of Docker Engine 29.6.1 for the Pilot app store",
          "Linux hosts only (arm64 + amd64) — daemon requires a Linux kernel",
          "Full docker CLI via verbatim-argv passthrough"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "proc.exec:docker",
      "net.dial:127.0.0.1",
      "fs.read:*",
      "fs.write:$APP",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "linux-arm64",
        "bytes": 46024000
      },
      {
        "platform": "linux-amd64",
        "bytes": 46024000
      }
    ],
    "installedBytes": 88910000,
    "rating": 5,
    "ratingCount": 1299,
    "ratingHistogram": [
      35,
      52,
      227,
      396,
      588
    ],
    "downloads": 44720,
    "depends": [],
    "protection": "guarded",
    "featured": true,
    "editorsChoice": false,
    "isNew": false,
    "real": true,
    "icon": {
      "mode": "mask",
      "img": null,
      "fit": null,
      "pos": null,
      "color": "#2496ED",
      "ink": false,
      "file": "/appicons/io.pilot.docker.svg",
      "hue": 30
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "native-cli"
    ],
    "publishedAt": "2026-06-30",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "io.pilot.aegis",
    "name": "AEGIS",
    "tagline": "Runtime firewall for AI agents",
    "description": "AEGIS is a runtime firewall for AI agents. It intercepts prompt injection, jailbreaks, homoglyph attacks, and infrastructure-impersonation at every agent input surface — inbox messages, tool results, skill files, memory notes — before the agent reads them.\n\nAn 880 KB Rust binary, fully offline: 90% recall and 95% precision on a held-out attack corpus. No network calls, no model — deterministic checks that run inline on every input.",
    "categories": [
      "security"
    ],
    "primaryCategory": "security",
    "keywords": [
      "security",
      "firewall",
      "prompt-injection",
      "jailbreak",
      "guardrail",
      "defense"
    ],
    "version": "0.1.4",
    "vendor": "Pilot Protocol",
    "vendorUrl": "https://aegis.pilotprotocol.network",
    "license": "Apache-2.0",
    "sourceUrl": "https://github.com/pilot-protocol/aegis",
    "homepage": "https://aegis.pilotprotocol.network",
    "methods": [
      {
        "name": "aegis.scan",
        "summary": "Scan an input for prompt injection, jailbreaks, homoglyphs, and impersonation."
      },
      {
        "name": "aegis.guard",
        "summary": "Wrap an input surface so every message is checked before the agent reads it."
      },
      {
        "name": "aegis.status",
        "summary": "Report firewall status and recent verdicts."
      },
      {
        "name": "aegis.help",
        "summary": "Discovery: every method with params and latency class."
      }
    ],
    "changelog": [
      {
        "version": "0.1.4",
        "date": "2026-06-29",
        "notes": [
          "Runtime firewall: prompt-injection, jailbreak, homoglyph, and impersonation detection at every input surface",
          "880 KB Rust binary, fully offline",
          "90% recall / 95% precision on the held-out corpus"
        ]
      }
    ],
    "grants": [
      "fs.read:$APP/config.json",
      "audit.log:*"
    ],
    "bundles": [
      {
        "platform": "darwin-arm64",
        "bytes": 2162000
      },
      {
        "platform": "darwin-amd64",
        "bytes": 2070000
      },
      {
        "platform": "linux-arm64",
        "bytes": 2369000
      },
      {
        "platform": "linux-amd64",
        "bytes": 2369000
      }
    ],
    "installedBytes": 900000,
    "rating": 5,
    "ratingCount": 468,
    "ratingHistogram": [
      11,
      4,
      72,
      154,
      228
    ],
    "downloads": 24119,
    "depends": [],
    "protection": "shareable",
    "featured": false,
    "editorsChoice": false,
    "isNew": true,
    "real": true,
    "icon": {
      "mode": "image",
      "img": "/appicons/io.pilot.aegis.svg",
      "fit": "contain",
      "pos": "center",
      "color": "#ffffff",
      "ink": false,
      "file": null,
      "hue": 5
    },
    "minPilotVersion": "1.0.0",
    "runtimes": [
      "native-cli"
    ],
    "publishedAt": "2026-06-29",
    "updatedAt": "2026-06-29"
  }
];

export const featuredOrder: string[] = ["io.pilot.postgres","io.pilot.duckdb","io.pilot.docker"];

// ---- derived helpers ----
const byId = new Map(apps.map((a) => [a.id, a]));
export function getApp(id: string): App | undefined { return byId.get(id); }
export function appsByCategory(cat: string): App[] {
  return apps.filter((a) => a.categories.includes(cat));
}
export function featuredApps(): App[] {
  const ordered = featuredOrder.map((id) => byId.get(id)).filter(Boolean) as App[];
  const rest = apps.filter((a) => a.featured && !featuredOrder.includes(a.id));
  return [...ordered, ...rest];
}
export function editorsChoice(): App[] { return apps.filter((a) => a.editorsChoice); }
export function newApps(): App[] { return apps.filter((a) => a.isNew); }
export function dependents(id: string): App[] {
  return apps.filter((a) => a.depends.some((d) => d.id === id));
}
export function relatedApps(app: App, limit = 6): App[] {
  return apps
    .filter((a) => a.id !== app.id && a.categories.some((c) => app.categories.includes(c)))
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit);
}
